### ISSUE TITLE
Make Error After running script

### ISSUE THREAD

**Issue by YsnSen** [bakkeby/flexipatch-finalizer#4] opened 2020-09-24 12:48 UTC
I am having `MakeFile:58: *** extraneous 'endif'. Stop.` error after using the script.

This is my make file.

`# dwm - dynamic window manager
# See LICENSE file for copyright and license details.

include config.mk

SRC = drw.c dwm.c util.c
OBJ = ${SRC:.c=.o}

# FreeBSD users, prefix all ifdef, else and endif statements with a . for this to work (e.g. .ifdef)

ifdef YAJLLIBS
all: options dwm dwm-msg
else
all: options dwm
endif

options:
	@echo dwm build options:
	@echo "CFLAGS   = ${CFLAGS}"
	@echo "LDFLAGS  = ${LDFLAGS}"
	@echo "CC       = ${CC}"

.c.o:
	${CC} -c ${CFLAGS} $<

${OBJ}: config.h config.mk

config.h:
	cp config.def.h $@

dwm: ${OBJ}
	${CC} -o $@ ${OBJ} ${LDFLAGS}

ifdef YAJLLIBS
dwm-msg:
	${CC} -o $@ patch/ipc/dwm-msg.c ${LDFLAGS}
endif

clean:
	rm -f dwm ${OBJ} dwm-${VERSION}.tar.gz
	rm -f dwm-msg

dist: clean
	mkdir -p dwm-${VERSION}
	cp -R LICENSE Makefile README config.def.h config.mk\
		dwm.1 drw.h util.h ${SRC} dwm.png transient.c dwm-${VERSION}
	tar -cf dwm-${VERSION}.tar dwm-${VERSION}
	gzip dwm-${VERSION}.tar
	rm -rf dwm-${VERSION}

install: all
	mkdir -p ${DESTDIR}${PREFIX}/bin
	cp -f dwm ${DESTDIR}${PREFIX}/bin
ifdef YAJLLIBS
	cp -f dwm-msg ${DESTDIR}${PREFIX}/bin
endif
	chmod 755 ${DESTDIR}${PREFIX}/bin/dwm-msg
endif
	mkdir -p ${DESTDIR}${MANPREFIX}/man1
	sed "s/VERSION/${VERSION}/g" < dwm.1 > ${DESTDIR}${MANPREFIX}/man1/dwm.1
	chmod 644 ${DESTDIR}${MANPREFIX}/man1/dwm.1

uninstall:
	rm -f ${DESTDIR}${PREFIX}/bin/dwm\
		${DESTDIR}${MANPREFIX}/man1/dwm.1

.PHONY: all options clean dist install uninstall`

I deleted the line 58 with `endif` it worked fine but I am not sure what caused the problem.

**Comment by bakkeby** [comment] 2020-09-24 13:22
Presumably you deleted one of the ifdef lines by mistake?

You have
```make
ifdef YAJLLIBS
cp -f dwm-msg ${DESTDIR}${PREFIX}/bin
endif
chmod 755 ${DESTDIR}${PREFIX}/bin/dwm-msg
endif
```
and seem to be missing this line:
https://github.com/bakkeby/dwm-flexipatch/blob/master/Makefile#L62

**Comment by YsnSen** [comment] 2020-09-24 13:37
dwm-flexipatch complies and runs fine. After I use the finalizer script with -o /newdirectory I got this error.
Adding `ifdef YAJLLIBS` to newly created makefile solved the mentioned problem but now it give the `make: *** [Makefile:24: dwm.o] Error 1` error.

**Comment by bakkeby** [comment] 2020-09-24 13:49
I can't replicate this.

You may want to run a
```bash
make clean && make
```
if there was problems with a previous build.

**Comment by YsnSen** [comment] 2020-09-24 14:31
I have just tried the script with a clean build of dwm-flexipatch  with the command `flexipatch-finalizer.sh -r -d /home/yasin/dwm-flexipatch -o /home/yasin/dwm-6.2` and still got a bad result.

I believe this problem is happening because of my lack of knowledge of linux.

If you want to check it out regardless I uploaded it to github. 

This is build I am running the script [https://github.com/KirliAdam/dwm-flexipatch](https://github.com/KirliAdam/dwm-flexipatch)

This is the result I am getting [https://github.com/KirliAdam/dwm-6.2](https://github.com/KirliAdam/dwm-6.2)

**Comment by bakkeby** [comment] 2020-09-24 14:57
No I don't think it has anything to do with any lack of knowledge of linux :)

I see what the issue is now, will commit a fix.

**Comment by bakkeby** [comment] 2020-09-24 15:01
I have pushed a fix for that now, thanks for reporting.

I also noticed another issue when using the IPC patch https://github.com/bakkeby/flexipatch-finalizer/issues/5 that I'll have to look into later.

**Comment by YsnSen** [comment] 2020-09-27 12:38
I have been using the scripts passed three days with different combinations of patches. I got no errors and results were able to install clean dwm code perfectly.

**Closed as completed** 2022-02-22 08:30 UTC
